In [46]:
# Installation

In [ ]:
pip install opencv-python

In [1]:
pip install opencv-contrib-python

Note: you may need to restart the kernel to use updated packages.


In [7]:
import cv2
img=cv2.imread("wallpaper.png")
cv2.imshow("ghibili",img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Read and Show Images

In [13]:
# Read and Show Images
import cv2
img=cv2.imread("wallpaper.png") # Read Image
cv2.imshow("ghibili",img) # Show Image 
cv2.waitKey(0) # given time to still window if we enter 0 then image is still open till pressed any key
cv2.destroyAllWindows() # All Windows Closed
#cv2.destroyWindow("wallpaper.png")# Close One Window Only by given image name

# Size in cv

In [25]:
# size 
import cv2
import numpy as np
img=cv2.imread("wallpaper.png") # Read Image
re_img=cv2.resize(img,(500,700))# change size 
cv2.imshow("ghibili",re_img) # Show Image 
cv2.waitKey(0) # given time to still window if we enter 0 then image is still open till pressed any key
cv2.destroyAllWindows() # All Windows Closed
#cv2.destroyWindow("wallpaper.png")# Close One Window Only by given image name




# find pixel in cv

In [40]:
# Find Pixle
img = cv2.imread(r"D:\dowl\image for studio\ph1.jpeg")
print(img)# it prints pixle of image



[[[34 29 20]
  [34 29 20]
  [34 29 20]
  ...
  [27 24 16]
  [26 23 15]
  [26 23 15]]

 [[34 29 20]
  [34 29 20]
  [34 29 20]
  ...
  [27 24 16]
  [26 23 15]
  [26 23 15]]

 [[34 29 20]
  [34 29 20]
  [34 29 20]
  ...
  [27 24 16]
  [27 24 16]
  [27 24 16]]

 ...

 [[40 32 19]
  [40 32 19]
  [41 33 20]
  ...
  [34 31 23]
  [34 31 23]
  [34 31 23]]

 [[40 32 19]
  [40 32 19]
  [41 33 20]
  ...
  [34 31 23]
  [34 31 23]
  [34 31 23]]

 [[40 32 19]
  [40 32 19]
  [41 33 20]
  ...
  [34 31 23]
  [34 31 23]
  [34 31 23]]]


# multiple image in one window

In [52]:
# multiple image in one window
import cv2
import numpy as np
img=cv2.imread(r"D:\dowl\image for studio\ph1.jpeg") # Read Image
re_img=cv2.resize(img,(300,300))# change size 
h=np.hstack((re_img,re_img,re_img,re_img,re_img))
v=np.vstack((h,h))
cv2.imshow("ghibili",v) # Show Image 
cv2.waitKey(0) # given time to still window if we enter 0 then image is still open till pressed any key
cv2.destroyAllWindows()

# Creating Slideshow 

In [8]:
# Creating Slideshow 
import cv2
import numpy as np
import os
list_name=os.listdir(r"D:\dowl\image for studio")
for name in list_name:
    path="D:\\dowl\\image for studio"
    img_name=path+"\\"+name
    img=cv2.imread(img_name)
    img=cv2.resize(img,(500,600))
    cv2.imshow("ghibili",img)
    cv2.waitKey(0)
cv2.destroyAllWindows()

# details of read and show and color grading

### Read and Show Images in details and rgb 

In [3]:
# 0 for GreyScale
import cv2
import numpy as np
img=cv2.imread("wallpaper.png",0) # Read Image
print(img.shape)
re_img=cv2.resize(img,(500,700))# change size 
cv2.imshow("ghibili",re_img) # Show Image 
cv2.waitKey(0) # given time to still window if we enter 0 then image is still open till pressed any key
cv2.destroyAllWindows() # All Windows Closed


(481, 490)


In [5]:
import cv2
import numpy as np
img=cv2.imread("wallpaper.png",1) # Read Image
print(img.shape)
re_img=cv2.resize(img,(500,700))# change size 
cv2.imshow("ghibili",re_img) # Show Image 
cv2.waitKey(0) # given time to still window if we enter 0 then image is still open till pressed any key
cv2.destroyAllWindows() # All Windows Closed


(481, 490, 3)


# Text on Image

In [21]:
import cv2
import numpy as np
img_get=cv2.imread(r"D:\dowl\image for studio\ph1.jpeg") # Read Image
txt=cv2.putText(img=img_get,
text='engineer',
org=(50,50),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale=1,
color=(0,0,25),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)
re_img=cv2.resize(txt,(800,700))# change size 
cv2.imshow("ghibili",re_img) # Show Image 
cv2.waitKey(0) # given time to still window if we enter 0 then image is still open till pressed any key
cv2.destroyAllWindows() # All Windows Closed


# Draw line and Rectangle on Image

### Draw Line

In [126]:
# Read and Show Images
import cv2
img1=cv2.imread("wallpaper.png")
new_img=cv2.line(img=img1,pt1=(210,100),pt2=(350,100),color=(0,255,0),thickness=4,lineType=4)
cv2.imshow("ghibili",new_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()


### Draw Rectangle

In [127]:
# Read and Show Images
import cv2
img2=cv2.imread("wallpaper.png")
txt=cv2.putText(img=img2,
text='DIPU',
org=(150,30),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale=1,
color=(0,255,0),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)
new_img2=cv2.rectangle(img=txt,pt1=(150,40),pt2=(370,270),color=(0,255,0),thickness=4,lineType=4)
cv2.imshow("ghibili",new_img2) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Draw Circle and Ellipse on Image

### Draw Circle

In [128]:
# Read and Show Images
import cv2
img1=cv2.imread("wallpaper.png")
txt=cv2.putText(img=img1,
text='DIPU',
org=(50,190),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale=1,
color=(0,255,0),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)
new_img=cv2.circle(img=txt,center=(260,150),radius=130,color=(0,255,0),thickness=4,lineType=4)
cv2.imshow("ghibili",new_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

#### hide face through circle

In [129]:
# Read and Show Images
import cv2
img1=cv2.imread("wallpaper.png")
txt=cv2.putText(img=img1,
text='DIPU',
org=(50,190),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale=1,
color=(0,255,0),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)
new_img=cv2.circle(img=txt,center=(260,150),radius=130,color=(0,255,0),thickness=-1,lineType=4)#set thickness to -1
cv2.imshow("ghibili",new_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### Draw Ellipse

In [130]:
# Read and Show Images
import cv2
img1=cv2.imread("wallpaper.png")
txt=cv2.putText(img=img1,
text='DIPU',
org=(50,190),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale=1,
color=(0,255,0),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)
new_img=cv2.ellipse(img=txt,center=(250,150),axes=(110,150),angle=170,startAngle=0,endAngle=360,color=(0,255,0),thickness=4,lineType=4)
cv2.imshow("ghibili",new_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

#### hide face through ellipse

In [131]:
import cv2
img1=cv2.imread("wallpaper.png")
txt=cv2.putText(img=img1,
text='DIPU',
org=(50,190),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale=1,
color=(0,255,0),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)
new_img=cv2.ellipse(img=txt,center=(250,150),axes=(110,150),angle=170,startAngle=0,endAngle=360,color=(0,255,0),thickness=-1,lineType=4)#set thickness to -1
cv2.imshow("ghibili",new_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Draw Polygons on Image

In [27]:
import cv2
import numpy as np
img1=cv2.imread("wallpaper.png")
txt=cv2.putText(img=img1,
text='DIPU',
org=(50,190),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale=1,
color=(0,255,0),
thickness=3,
lineType=cv2.LINE_8,
bottomLeftOrigin=False)
new_img=cv2.polylines(img=txt,pts=[np.array([[50,150],[100,200],[150,250],[250,300],[350,350]])],isClosed=True,color=(0,255,0),thickness=2,lineType=4)#set thickness to -1
cv2.imshow("ghibili",new_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Arithmetic Operations in Open CV

In [43]:
import cv2
img1=cv2.imread("wallpaper.png")
img2=cv2.imread("inside.png")
re_img1=cv2.resize(img1,(500,500))# change size 
re_img2=cv2.resize(img2,(500,500))# change size
new_img=cv2.addWeighted(re_img1,0.3,re_img2,15,10)
cv2.imshow("ghibili",new_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [48]:
import cv2
img1=cv2.imread("wallpaper.png")
img2=cv2.imread("inside.png")
re_img1=cv2.resize(img1,(500,500))# change size 
re_img2=cv2.resize(img2,(500,500))# change size
new_img=cv2.subtract(re_img1,re_img2)
cv2.imshow("ghibili",new_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Bitwise Operations on Images

### And

In [57]:
import cv2
import numpy as np

img1=cv2.imread("binary image 1.png")
img2=cv2.imread("binary image 2.png")

re_img1=cv2.resize(img1,(500,500))
re_img2=cv2.resize(img2,(500,500))

new=cv2.bitwise_and(re_img1,re_img2)
h = np.hstack((re_img1,re_img2,new))

cv2.imshow("ghibili",h) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### Or

In [58]:
import cv2
import numpy as np

img1 = cv2.imread("binary image 1.png")
img2 = cv2.imread("binary image 2.png")


re_img1 = cv2.resize(img1, (500, 500))  
re_img2 = cv2.resize(img2, (500, 500))  

new = cv2.bitwise_or(re_img1, re_img2)

h = np.hstack((re_img1, re_img2, new)) 

cv2.imshow("ghibili", h)  
cv2.waitKey(0)
cv2.destroyAllWindows()

### NOT

In [74]:
import cv2
import numpy as np

img2 = cv2.imread("wallpaper.png")


re_img2 = cv2.resize(img2, (500, 500))  

new = cv2.bitwise_not(re_img2)

h = np.hstack((re_img2, new)) 

cv2.imshow("ghibili", h)  
cv2.waitKey(0)
cv2.destroyAllWindows()

In [64]:
import cv2
import numpy as np

img2 = cv2.imread("binary image 2.png")


re_img2 = cv2.resize(img2, (500, 500))  

new = cv2.bitwise_not(re_img2)

h = np.hstack((re_img2, new)) 

cv2.imshow("ghibili", h)  
cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
import cv2
import numpy as np

img1 = cv2.imread("binary image 1.png")



re_img1 = cv2.resize(img1, (500, 500))  


new = cv2.bitwise_not(re_img1)

h = np.hstack((re_img1, new)) 

cv2.imshow("ghibili", h)  
cv2.waitKey(0)
cv2.destroyAllWindows()

### XOR

In [72]:
import cv2
import numpy as np

img1 = cv2.imread("binary image 1.png")
img2 = cv2.imread("binary image 2.png")


re_img1 = cv2.resize(img1, (500, 500))  
re_img2 = cv2.resize(img2, (500, 500))  

new = cv2.bitwise_xor(re_img1, re_img2)

h = np.hstack((re_img1, re_img2, new)) 

cv2.imshow("ghibili", h)  
cv2.waitKey(0)
cv2.destroyAllWindows()

# Edge Detection

In [3]:
import cv2
import numpy as np

img1 = cv2.imread("wallpaper.png")
print(img1.shape)
re_img1 = cv2.resize(img1, (500, 500))  
nimg=cv2.Canny(re_img1,50,50)
cv2.imshow("new",nimg)
cv2.waitKey(0)
cv2.destroyAllWindows()

(481, 490, 3)


### Reduce Frequency of Edge

In [5]:
import cv2
import numpy as np

img1 = cv2.imread("wallpaper.png")
print(img1.shape)

img1 = cv2.resize(img1, (500, 500))  

nimg=cv2.Canny(img1,100,100,apertureSize=7,L2gradient=True)
print(nimg.shape)

cv2.imshow("new",nimg)
cv2.waitKey(0)
cv2.destroyAllWindows()

(481, 490, 3)
(500, 500)


# Image Scaling and Rotating

### Scaling

In [11]:
import cv2
img=cv2.imread("wallpaper.png")
img1 = cv2.resize(img, (1000, 1000))
cv2.imshow("ghibili",img1) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### Rotating

In [20]:
import cv2
# Read the image file
img = cv2.imread("wallpaper.png")

# Resize the image to 500x500 pixels
img1 = cv2.resize(img, (500, 500))

# Get the dimensions of the resized image
# Note: OpenCV stores images as height x width (rows x columns)
w, h = img1.shape[0], img1.shape[1]
print(w, h)

# Create a rotation matrix
# Parameters: center point (x,y), angle of rotation (40 degrees), scale factor (0)
m = cv2.getRotationMatrix2D((w/2, h/2), 40, 0)

# Apply affine transformation (rotation in this case)
# cv2.warpAffine expects dsize as (width, height) tuple
# This is why we pass (h, w) instead of (w, h)
nimg = cv2.warpAffine(img1, m, (h, w))

# Display the rotated image
cv2.imshow("ghibili", nimg) 

# Wait for a key press (0 means wait indefinitely)
cv2.waitKey(0)

# Close all OpenCV windows
cv2.destroyAllWindows()

500 500


# Image Blurring

### Gaussian Blur

In [39]:
import cv2
import numpy as np

# Read the image file from disk

img = cv2.imread("wallpaper.png")

# Resize the image to 500x500 pixels
# Parameters: source image, target size (width, height)

img1 = cv2.resize(img, (500, 500))

# Apply Gaussian Blur to reduce noise and detail in the image
# Parameters:
# - source image
# - kernel size (must be odd numbers) - larger values create more blur
# - sigma (standard deviation) - 0 means it's calculated from kernel size


g = cv2.GaussianBlur(img1, (117, 117), 0)

# Display the blurred image in a window titled "ghibili"

cv2.imshow("ghibili", g) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### Median Blur

In [40]:
import cv2
import numpy as np

# Read the image file from disk

img = cv2.imread("wallpaper.png")

# Resize the image to 500x500 pixels
# Parameters: source image, target size (width, height)

img1 = cv2.resize(img, (500, 500))

# Apply Gaussian Blur to reduce noise and detail in the image
# Parameters:
# - source image
# - kernel size (must be odd numbers) - larger values create more blur
# - sigma (standard deviation) - 0 means it's calculated from kernel size


g = cv2.medianBlur(img1,117, 0)

# Display the blurred image in a window titled "ghibili"

cv2.imshow("ghibili", g) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### Bilateral Filter

In [51]:
import cv2
import numpy as np

# Read the image file from disk

img = cv2.imread("wallpaper.png")

# Resize the image to 500x500 pixels
# Parameters: source image, target size (width, height)

img1 = cv2.resize(img, (500, 500))

# Apply Gaussian Blur to reduce noise and detail in the image
# Parameters:
# - source image
# - kernel size (must be odd numbers) - larger values create more blur
# - sigma (standard deviation) - 0 means it's calculated from kernel size


g = cv2.bilateralFilter(img1,90,99,99)

# Display the blurred image in a window titled "ghibili"

cv2.imshow("ghibili", g) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Save Photo in Gallery

In [2]:
import cv2
import numpy as np

img = cv2.imread("wallpaper.png")
img1 = cv2.resize(img, (500, 500))
g = cv2.bilateralFilter(img1, 90, 99, 99)

cv2.imwrite(r"D:\dowl\image for studio\blur.png",g)
cv2.imshow("ghibili", g) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Make Border in CV

In [10]:
import cv2
import numpy as np

img = cv2.imread("wallpaper.png")
img1 = cv2.resize(img, (500, 500))
nimg=cv2.copyMakeBorder(img1,20,20,20,20,cv2.BORDER_CONSTANT,None,value=2)
cv2.imshow("ghibili",nimg ) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Play Vedio Using CV

In [27]:
import cv2
import numpy as np

vid = cv2.VideoCapture(r"C:\Users\MSI1\OneDrive\圖片\Camera Roll\WIN_20250704_15_22_24_Pro.mp4")
while vid.isOpened():
    r,frame=vid.read()
    if r==True:
        cv2.imshow("h",frame)
        if cv2.waitKey(0) & 0xff==ord("p"):
            break
    else:
        break
vid.release()
cv2.destroyAllWindows()

In [30]:
import cv2
import numpy as np

# Fix 1: Use raw string (r prefix) or double backslashes or forward slashes for the file path
vid = cv2.VideoCapture(r"C:\Users\MSI1\OneDrive\圖片\Camera Roll\WIN_20250704_15_22_24_Pro.mp4")
# Alternative: vid = cv2.VideoCapture("C:\\Users\\MSI1\\OneDrive\\圖片\\Camera Roll\\WIN_20250704_15_22_24_Pro.mp4")
# Alternative: vid = cv2.VideoCapture("C:/Users/MSI1/OneDrive/圖片/Camera Roll/WIN_20250704_15_22_24_Pro.mp4")

# Fix 2: Correct method name from 'vidisOpened()' to 'vid.isOpened()'
while vid.isOpened():
    r, frame = vid.read()
    if r == True:
        frame=cv2.resize(frame,(500,500))
        # Fix 3: Use 'frame' variable instead of undefined 'f'
        cv2.imshow("h", frame)
        # Fix 4: For video playback, use a small delay (e.g., 25) instead of 0
        if cv2.waitKey(25) & 0xff == ord("p"):
            break
    else:
        break
        
vid.release()
cv2.destroyAllWindows()


# Capture Vedio from open CV

In [35]:
import cv2
import numpy as np

vid = cv2.VideoCapture(0)
while True:
    r,frame=vid.read()
    if r==True:
        cv2.imshow("h",frame)
        if cv2.waitKey(25) & 0xff==ord("p"):
            break
    else:
        break
vid.release()
cv2.destroyAllWindows()

# Slomo & Fastmo

### while recorded vedio

In [36]:
import cv2
import numpy as np

vid = cv2.VideoCapture(r"C:\Users\MSI1\OneDrive\圖片\Camera Roll\WIN_20250704_15_22_24_Pro.mp4")


while vid.isOpened():
    r, frame = vid.read()
    if r == True:
        frame=cv2.resize(frame,(500,500))
        cv2.imshow("h", frame)
        if cv2.waitKey(10) & 0xff == ord("p"):
            break
    else:
        break
        
vid.release()
cv2.destroyAllWindows()

# increase for slow & decrease for fast in wait key and 0 for static()

### While Capture

In [41]:
import cv2
import numpy as np

vid = cv2.VideoCapture(0)
while True:
    r,frame=vid.read()
    if r==True:
        cv2.imshow("h",frame)
        if cv2.waitKey(1000) & 0xff==ord("p"):
            break
    else:
        break
vid.release()
cv2.destroyAllWindows()
# increase for slow & decrease for quick not fast and 0 for static in wait key()

# Morphological Operations

### Erosion

In [15]:
import cv2
import numpy as np

img=cv2.imread("j_b.png")
re_img=cv2.resize(img,(500,700))

m=np.ones((15,15),np.int8)
er=cv2.erode(re_img,m,iterations=1)

cv2.imshow("ghibili",er) 
cv2.imshow("ghibili2",re_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### Dilation

In [16]:
import cv2
import numpy as np

img=cv2.imread("j_b.png")
re_img=cv2.resize(img,(500,700))

m=np.ones((15,15),np.int8)
er=cv2.dilate(re_img,m,iterations=1)

cv2.imshow("ghibili",er) 
cv2.imshow("ghibili2",re_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### Opening Noise Removing

In [22]:
import cv2
import numpy as np

img=cv2.imread("j_w_b.png")
re_img=cv2.resize(img,(500,700))

m=np.ones((15,15),np.int8)
op=cv2.morphologyEx(re_img,cv2.MORPH_OPEN,m,iterations=1)

cv2.imshow("ghibili",op) 
cv2.imshow("ghibili2",re_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### Closing Noise Removing 

In [24]:
import cv2
import numpy as np

img=cv2.imread("j_b_b.png")
re_img=cv2.resize(img,(500,700))

m=np.ones((15,15),np.int8)
op=cv2.morphologyEx(re_img,cv2.MORPH_CLOSE,m,iterations=1)

cv2.imshow("ghibili",op) 
cv2.imshow("ghibili2",re_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### Morphological Gradient

In [26]:
import cv2
import numpy as np

img=cv2.imread("j_b.png")
re_img=cv2.resize(img,(500,700))

m=np.ones((15,15),np.int8)
op=cv2.morphologyEx(re_img,cv2.MORPH_GRADIENT,m,iterations=1)

cv2.imshow("ghibili",op) 
cv2.imshow("ghibili2",re_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

### TOP HAT

In [36]:
import cv2
import numpy as np

img=cv2.imread("j_b.png")
re_img=cv2.resize(img,(500,700))

m=np.ones((35,35),np.int8)
op=cv2.morphologyEx(re_img,cv2.MORPH_TOPHAT,m,iterations=1)

cv2.imshow("ghibili",op) 
cv2.imshow("ghibili2",re_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
### BLACK HAT

In [42]:
import cv2
import numpy as np

img=cv2.imread("j_b.png")
re_img=cv2.resize(img,(500,700))

m=np.ones((40,40),np.int8)
op=cv2.morphologyEx(re_img,cv2.MORPH_BLACKHAT,m,iterations=1)

cv2.imshow("ghibili",op) 
cv2.imshow("ghibili2",re_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

# Image Pyramid

In [52]:
import cv2
import numpy as np

img=cv2.imread("wallpaper.png")
print(img.shape)

new=cv2.pyrDown(img)
print(new.shape)


cv2.imshow("ghibili2",new)
cv2.imshow("ghibili",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

(481, 490, 3)
(241, 245, 3)


# Image Translation(crop)

In [53]:
import cv2
import numpy as np

img=cv2.imread("wallpaper.png")
re_img=cv2.resize(img,(500,700))

m=np.float32([[1,0,100],[0,1,50]])
new=cv2.warpAffine(re_img,m,(500,500))



cv2.imshow("ghibili2",new)
cv2.imshow("ghibili",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Geometric Transformation of Image and Background Substraction

In [8]:
import cv2
import numpy as np

vid = cv2.VideoCapture(r"C:\Users\MSI1\OneDrive\Desktop\Untitled video - Made with Clipchamp.mp4")
subm=cv2.createBackgroundSubtractorMOG2()

while True:
    r, frame = vid.read()
    if r == True:
        frame=cv2.resize(frame,(700,500))
        subv=subm.apply(frame)
        cv2.imshow("dupl", subv)
        cv2.imshow("org", frame)
        if cv2.waitKey(10) & 0xff == ord("p"):
            break
    else:
        break
        
vid.release()
cv2.destroyAllWindows()

# Extract Image From Vedio

In [13]:
import cv2
import numpy as np

vid = cv2.VideoCapture(r"C:\Users\MSI1\OneDrive\Desktop\Untitled video - Made with Clipchamp.mp4")
c=0

while True:
    r, frame = vid.read()
    if r == True:
        frame=cv2.resize(frame,(700,500))
        filename="D://dowl//image for studio//org"+str(c)+".png"
        cv2.imwrite(filename,frame)
        c=c+1
        cv2.imshow("org", frame)
        if cv2.waitKey(15) & 0xff == ord("p"):
            break
    else:
        break
        
vid.release()
cv2.destroyAllWindows()

# cvtColor Method

In [6]:
import cv2
import numpy as np

img1 = cv2.imread("wallpaper.png")
img1 = cv2.resize(img1, (400, 400))  

new=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)

cv2.imshow("new",new)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Crop Image in CV

In [23]:
import cv2
import numpy as np

img1 = cv2.imread("wallpaper.png")
img1 = cv2.resize(img1, (500, 500))  

crop=img1[150:180,200:350]

cv2.imshow("new",crop)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Create Blank Image

### White

In [27]:
import cv2
import numpy as np

newimg=np.ones((500,500,3),np.uint8)*255

cv2.imshow("new",newimg)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Black

In [29]:
import cv2
import numpy as np

newimg=np.zeros((500,500,3),np.uint8)*255

cv2.imshow("new",newimg)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Color Picker

In [3]:
import cv2
import numpy as np

def xfun(x):
    pass

img=np.zeros((500,500,3),np.uint8)*255

cv2.namedWindow("Pick your Colour")

cv2.createTrackbar("R","Pick your Colour",0,255,xfun)
cv2.createTrackbar("B","Pick your Colour",0,255,xfun)
cv2.createTrackbar("G","Pick your Colour",0,255,xfun)

while True:
    cv2.imshow("name",img)
    if cv2.waitKey(1) & 0xff==ord("x"):
        break
    r=cv2.getTrackbarPos("R","Pick your Colour")
    g=cv2.getTrackbarPos("B","Pick your Colour")
    b=cv2.getTrackbarPos("G","Pick your Colour")
    img[:]=[b,g,r]

cv2.destroyAllWindows()

# getTrackbarPos() Function

In [13]:
import cv2
import numpy as np

def xfun(x):
    pass

img=np.zeros((500,500,3),np.uint8)

cv2.namedWindow("Pick your Colour")
cv2.createTrackbar("on","Pick your Colour",0,255,xfun)


while True:
    cv2.imshow("name",img)
    if cv2.waitKey(1) & 0xff==ord("x"):
        break
    var=cv2.getTrackbarPos("on","Pick your Colour")
    img[:]=[var,0,0]#b
    #img[:]=[0,var,0]#g
    #img[:]=[0,0,var]#r
cv2.destroyAllWindows()

# Region of Intrest    😡😤😎👨‍🦱😉😊👿

In [25]:
import cv2

img = cv2.imread("save.png")
crop = img[30:280, 160:350]  # This creates a crop of shape (250, 190, 3)

# Fix: Adjust the destination region to match the crop's dimensions
# The destination region must have the same width as the crop (190 pixels)
# So we change from img[30:280, 352:550] to img[30:280, 352:542]
img[30:280, 352:542] = crop  # 352 + 190 = 542

cv2.imshow("ghibili", crop)
cv2.waitKey(0)
cv2.destroyAllWindows()

Image too small! Width: 500, needed: at least 542


# Flip Rotate Transpose

### Flip

In [36]:
import cv2

img = cv2.imread("save.png")
img = cv2.resize(img, (500, 500))  

img=cv2.flip(img,1)

cv2.imshow("ghibili", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Rotate

In [39]:
import cv2

img = cv2.imread("save.png")
img = cv2.resize(img, (500, 500))  

img=cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)

cv2.imshow("ghibili", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
import cv2

img = cv2.imread("save.png")
img = cv2.resize(img, (500, 500))  

img=cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)

cv2.imshow("ghibili", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
import cv2

img = cv2.imread("save.png")
img = cv2.resize(img, (500, 500))  

img=cv2.rotate(img,cv2.ROTATE_180)

cv2.imshow("ghibili", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Transpose

In [44]:
import cv2

img = cv2.imread("save.png")
img = cv2.resize(img, (500, 500))  

img=cv2.transpose(img)

cv2.imshow("ghibili", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Flip and change color While Capture

In [49]:
import cv2
import numpy as np

vid = cv2.VideoCapture(0)
while True:
    r,frame=vid.read()
    if r==True:
        frame=cv2.flip(frame,1)
        frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

        cv2.imshow("h",frame)
        if cv2.waitKey(10) & 0xff==ord("p"):
            break
    else:
        break
vid.release()
cv2.destroyAllWindows()

# Record Capture with voice

In [52]:
import cv2
import numpy as np

vid = cv2.VideoCapture(0)
f=cv2.VideoWriter_fourcc(*"xvid")
out=cv2.VideoWriter("demo.mp4",f,10.0,(640,480))
while True:
    r,frame=vid.read()
    if r==True:
        frame=cv2.flip(frame,1)
        out.write(frame)
        cv2.imshow("h",frame)
        if cv2.waitKey(20) & 0xff==ord("p"):
            break
    else:
        break
vid.release()
out.release()
cv2.destroyAllWindows()

# Colors spaces in Vedio no voice

In [56]:
import cv2
import numpy as np

vid = cv2.VideoCapture(0)
while True:
    r,frame=vid.read()
    if r==True:
        frame=cv2.flip(frame,1)
        frame=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)

        cv2.imshow("h",frame)
        if cv2.waitKey(10) & 0xff==ord("p"):
            break
    else:
        break
vid.release()
cv2.destroyAllWindows()

# Color Filter

In [33]:
import cv2
import numpy as np

vid = cv2.VideoCapture(0)
def xfun(x):
    pass
cv2.namedWindow("demo")
cv2.createTrackbar("lb","demo",0,255,xfun)
cv2.createTrackbar("lg","demo",0,255,xfun)
cv2.createTrackbar("lr","demo",0,255,xfun)

cv2.createTrackbar("ub","demo",0,255,xfun)
cv2.createTrackbar("ug","demo",0,255,xfun)
cv2.createTrackbar("ur","demo",0,255,xfun)





while vid.isOpened():
    r,frame=vid.read()
    if r==True:
        img=cv2.resize(frame,(400,400))
        img=cv2.flip(img,1)
        hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
        lb=cv2.getTrackbarPos("lb","demo")
        lg=cv2.getTrackbarPos("lg","demo")
        lr=cv2.getTrackbarPos("lr","demo")
        
        ub=cv2.getTrackbarPos("ub","demo")
        ug=cv2.getTrackbarPos("ug","demo")
        ur=cv2.getTrackbarPos("ur","demo")

        lo=np.array([lb,lg,lr])
        up=np.array([ub,ug,ur])

        masks=cv2.inRange(hsv,lo,up)

        res=cv2.bitwise_and(img,img,mask=masks)
        
        cv2.imshow('res',res)
        cv2.imshow('masks',masks)
        cv2.imshow('hsv',hsv)
        cv2.imshow('hulooloo',img)

        if cv2.waitKey(10) & 0xff==ord("p"):
            break
    else:
        break
vid.release()
cv2.destroyAllWindows()

# Object Detection in vedios

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt


cap=cv2.VideoCapture(r"C:\Users\MSI1\OneDrive\Desktop\Untitled video - Made with Clipchamp.mp4")
r,f=cap.read()
x,y,w,h=250,220,400,400
t=(x,y,w,h)
roi=f[y:y+h,x:x+w]
hsv_roi=cv2.cvtColor(roi,cv2.COLOR_BGR2HSV)
mask=cv2.inRange(hsv_roi,np.array((0.,60.,32.)),np.array((180.,255.,255.)))
hist=cv2.calcHist([hsv_roi],[0],mask,[180],[0,180])
cv2.normalize(hist,hist,0,255,cv2.NORM_MINMAX)
ter=(cv2.TERM_CRITERIA_EPS  | cv2.TERM_CRITERIA_COUNT,10,1)





while cap.isOpened():
    r,f=cap.read()
    if  r==True:
        hsvf=cv2.cvtColor(f,cv2.COLOR_BGR2HSV)
        d=cv2.calcBackProject([hsvf],[0],hist,[0,180],1)
        r,tp=cv2.meanShift(d,t,ter)
        x,y,w,h=tp
        final=cv2.rectangle(f,(x,y),(x+w,y+h),(0,0,255),4)
        cv2.imshow("ghibili",final)
        if cv2.waitKey(15) & 0xff==ord("x"):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()


# Display color code and cooordinates of selected points using mouse

In [20]:
import cv2
def click_b(event,x,y,f,p):
    if event == cv2.EVENT_LBUTTONDOWN:
        s=f"{x},{y}"
        cv2.putText(img,s,(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
        cv2.imshow("ghibili",img) 
    elif event == cv2.EVENT_RBUTTONDOWN:
        b=img[y,x,0]
        g=img[y,x,1]
        r=img[y,x,2]
        s=f"{b},{g},{r}"
        cv2.putText(img,s,(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(145,255,255))
        cv2.imshow("ghibili",img) 



img=cv2.imread("wallpaper.png")
cv2.imshow("ghibili",img) 
cv2.setMouseCallback("ghibili",click_b)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Veichle Detection in vedio

In [4]:
import cv2
import numpy as np

vid = cv2.VideoCapture(r"D:\dowl\highway.mp4")
while True:
    r,frame=vid.read()
    if r==True:
        gry=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        car=cv2.CascadeClassifier(r"D:\dowl\haarcascade_car.xml")
        cars=car.detectMultiScale(gry,1.2,3)
        for(x,y,w,h) in cars:
            cv2.rectangle(frame,(x,y),(x+h,y+h),(0,0,255),3)
        frame=cv2.resize(frame,(700,500))
        cv2.imshow("h",frame)
        if cv2.waitKey(45) & 0xff==ord("p"):
            break
    else:
        break
vid.release()
cv2.destroyAllWindows()

# Veichle Detection in image

In [2]:
import cv2

img = cv2.imread(r"Screenshot 2025-07-14 133003.png")
img = cv2.resize(img, (700, 500))  
gry=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
car=cv2.CascadeClassifier(r"D:\dowl\haarcascade_car.xml")
cars=car.detectMultiScale(gry,1.2,3)
for(x,y,w,h) in cars:
            cv2.rectangle(img,(x,y),(x+h,y+h),(0,0,255),3)
cv2.imshow("ghibili", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Installation of Mediapipe for Advanced Detection

In [3]:
pip install mediapipe

Note: you may need to restart the kernel to use updated packages.


# Face Detection

In [12]:
import cv2
import mediapipe as mp

In [13]:
mp_face=mp.solutions.face_detection
mp_draw=mp.solutions.drawing_utils

In [14]:
face_dect=mp_face.FaceDetection(min_detection_confidence=1,model_selection=0)
vid = cv2.VideoCapture(0)
while True:
    r,frame=vid.read()
    frame=cv2.flip(frame,1)
    if r==True:
        frame=cv2.resize(frame,(700,500))
        result=face_dect.process(frame)
        if r==True:
            for cr in result.detections:
                mp_draw.draw_detection(frame,cr)
            
        cv2.imshow("h",frame)
        if cv2.waitKey(45) & 0xff==ord(" "):
            break
    else:
        break
vid.release()
cv2.destroyAllWindows()

TypeError: 'NoneType' object is not iterable

# Hand Tracking

In [2]:
import cv2
import mediapipe as mp
mp_draw=mp.solutions.drawing_utils
mp_drawing_styles=mp.solutions.drawing_styles
mp_hands=mp.solutions.hands
p=mp_hands.Hands(static_image_mode=True,max_num_hands=2,min_detection_confidence=0.5)
vid = cv2.VideoCapture(0)
while True:
    r,frame=vid.read()
    frame=cv2.flip(frame,1)
    if r==True:
        frame=cv2.resize(frame,(700,500))
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)  # Convert to RGB
        result=p.process(rgb_frame)
        if result.multi_hand_landmarks:
            for cr in result.multi_hand_landmarks:
                mp_draw.draw_landmarks(frame,cr,mp_hands.HAND_CONNECTIONS)
            
        cv2.imshow("h",frame)
        if cv2.waitKey(45) & 0xff==ord(" "):
            break
    else:
        break
vid.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
import mediapipe as mp

mp_draw = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

p = mp_hands.Hands(static_image_mode=True, max_num_hands=2, min_detection_confidence=0.5)

vid = cv2.VideoCapture(0)

while True:
    r, frame = vid.read()
    frame = cv2.flip(frame,1)

    if r==True:
        frame = cv2.resize(frame, (700, 500))
        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)  # Convert to RGB

        result = p.process(rgb_frame)

        if result.multi_hand_landmarks:
            for cr in result.multi_hand_landmarks:
                mp_draw.draw_landmarks(frame, cr, mp_hands.HAND_CONNECTIONS)

        cv2.imshow("Hand Detection", frame)

        if cv2.waitKey(45) & 0xFF == ord(" "):
            break
    else:
        break

vid.release()
cv2.destroyAllWindows()